import { Kelurahan, SnackboxProduct, DeliveryOption, PaymentMethodOption } from '@/types/snackbox'

export const mockKelurahans: Kelurahan[] = [
  {
    id: 'kel-menteng',
    name: 'Menteng',
    kecamatan: 'Menteng',
    kota: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    postalCode: '10310',
    itemCount: 18
  },
  {
    id: 'kel-tebet-barat',
    name: 'Tebet Barat',
    kecamatan: 'Tebet',
    kota: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postalCode: '12810',
    itemCount: 22
  },
  {
    id: 'kel-senayan',
    name: 'Senayan',
    kecamatan: 'Kebayoran Baru',
    kota: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postalCode: '12190',
    itemCount: 16
  },
  {
    id: 'kel-kelapa-gading-timur',
    name: 'Kelapa Gading Timur',
    kecamatan: 'Kelapa Gading',
    kota: 'Jakarta Utara',
    province: 'DKI Jakarta',
    postalCode: '14240',
    itemCount: 20
  },
  {
    id: 'kel-rawamangun',
    name: 'Rawamangun',
    kecamatan: 'Pulo Gadung',
    kota: 'Jakarta Timur',
    province: 'DKI Jakarta',
    postalCode: '13220',
    itemCount: 14
  },
  {
    id: 'kel-kebon-jeruk',
    name: 'Kebon Jeruk',
    kecamatan: 'Kebon Jeruk',
    kota: 'Jakarta Barat',
    province: 'DKI Jakarta',
    postalCode: '11530',
    itemCount: 15
  },
  {
    id: 'kel-bintaro',
    name: 'Bintaro',
    kecamatan: 'Pesanggrahan',
    kota: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postalCode: '12330',
    itemCount: 19
  },
  {
    id: 'kel-beji',
    name: 'Beji',
    kecamatan: 'Beji',
    kota: 'Kota Depok',
    province: 'Jawa Barat',
    postalCode: '16421',
    itemCount: 12
  }
]

export const defaultKelurahan: Kelurahan = mockKelurahans[0]

export const mockSnackboxProducts: SnackboxProduct[] = [
  // ── MENTENG (Aktif default) ──
  {
    id: 'sb-lemper-bakar-menteng',
    title: 'Lemper Bakar Ayam Suwir Spesial',
    description: 'Ketan pulen wangi daun pisang bakar dengan isian ayam suwir bumbu rempah gurih melimpah.',
    price: 6500,
    originalPrice: 7500,
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.9,
    reviewCount: 342,
    soldCount: 2840,
    isTrending: true,
    isBestSeller: true,
    tags: ['Favorit Rapat', 'Gurih', 'Fresh Setiap Pagi'],
    stock: 250,
    portionWeight: '75g'
  },
  {
    id: 'sb-risol-mayo-menteng',
    title: 'Risoles Ragout Smoked Beef & Mayo',
    description: 'Kulit lembut berbalut tepung roti renyah, isi smoked beef, telur rebus, dan mayo lumer gurih.',
    price: 7000,
    originalPrice: 8000,
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Gurih',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.8,
    reviewCount: 289,
    soldCount: 2190,
    isTrending: true,
    isBestSeller: true,
    tags: ['Crispy', 'Lumer', 'Snack Gurih'],
    stock: 300,
    portionWeight: '80g'
  },
  {
    id: 'sb-pie-buah-menteng',
    title: 'Pie Buah Segar Vanilla Custard',
    description: 'Tartlet renyah buttery dengan fla vanilla lembut berpadu potongan buah kiwi, strawberry, dan anggur.',
    price: 8500,
    originalPrice: 9500,
    imageUrl: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Manis',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.9,
    reviewCount: 412,
    soldCount: 3100,
    isTrending: true,
    isBestSeller: true,
    tags: ['Premium', 'Manis Segar', 'Favorit Acara'],
    stock: 200,
    portionWeight: '70g'
  },
  {
    id: 'sb-pastel-menteng',
    title: 'Pastel Ulir Renyah Isi Sayur Telur',
    description: 'Kulit pastry ulir renyah berlapis, isi wortel, kentang, soun, ayam, dan irisan telur rebus plus cabai rawit.',
    price: 5500,
    imageUrl: 'https://images.unsplash.com/photo-1608855238293-a8853e7f7c98?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Basah',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.8,
    reviewCount: 198,
    soldCount: 1720,
    isTrending: false,
    isBestSeller: false,
    tags: ['Tradisional', 'Gurih Renyah'],
    stock: 180,
    portionWeight: '70g'
  },
  {
    id: 'sb-fudgy-brownies-menteng',
    title: 'Fudgy Brownies Bites Choco Almond',
    description: 'Potongan brownies cokelat pekat chewy dengan shiny crust dan taburan almond panggang renyah.',
    price: 7500,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Kekinian',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.9,
    reviewCount: 520,
    soldCount: 3950,
    isTrending: true,
    isBestSeller: true,
    tags: ['Belgian Cocoa', 'Choco Lover'],
    stock: 220,
    portionWeight: '60g'
  },
  {
    id: 'sb-sosis-solo-menteng',
    title: 'Sosis Solo Kukus Daging Ayam Juara',
    description: 'Dadar telur tipis wangi lembut menggulung cincangan daging ayam bumbu gurih manis khas Solo.',
    price: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.8,
    reviewCount: 165,
    soldCount: 1430,
    isTrending: false,
    isBestSeller: false,
    tags: ['Khas Solo', 'Kukus Sehat'],
    stock: 150,
    portionWeight: '65g'
  },
  {
    id: 'sb-lapis-legit-menteng',
    title: 'Lapis Legit Mini Butter Wisman',
    description: 'Lapis legit berlapis rapi beraroma butter Wisman premium dan wangi spekuk rempah klasik.',
    price: 12000,
    originalPrice: 14000,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Basah',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 5.0,
    reviewCount: 180,
    soldCount: 1200,
    isTrending: false,
    isBestSeller: true,
    tags: ['Wisman Butter', 'Super Premium'],
    stock: 90,
    portionWeight: '55g'
  },
  {
    id: 'sb-dadar-gulung-menteng',
    title: 'Dadar Gulung Pandan Unti Kelapa',
    description: 'Kulit pandan suji berpori alami diisi parutan kelapa gula merah asli yang wangi dan lumer.',
    price: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-menteng',
    kelurahanName: 'Menteng',
    rating: 4.7,
    reviewCount: 142,
    soldCount: 1150,
    isTrending: false,
    isBestSeller: false,
    tags: ['Pandan Asli', 'Gula Aren'],
    stock: 160,
    portionWeight: '60g'
  },

  // ── TEBET BARAT ──
  {
    id: 'sb-bolu-kukus-tebet',
    title: 'Bolu Kukus Mawar Mekar Pelangi',
    description: 'Bolu kukus lembut merekah dengan motif bunga mawar warna-warni beraroma vanili harum.',
    price: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Basah',
    kelurahanId: 'kel-tebet-barat',
    kelurahanName: 'Tebet Barat',
    rating: 4.8,
    reviewCount: 270,
    soldCount: 2600,
    isTrending: true,
    isBestSeller: true,
    tags: ['Cantik', 'Lembut'],
    stock: 200,
    portionWeight: '50g'
  },
  {
    id: 'sb-kroket-tebet',
    title: 'Kroket Kentang Belanda Isi Ragout Daging',
    description: 'Olahan kentang tumbuk halus lembut dibalut remah roti gurih, isi cincangan daging sapi wortel.',
    price: 7500,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Gurih',
    kelurahanId: 'kel-tebet-barat',
    kelurahanName: 'Tebet Barat',
    rating: 4.9,
    reviewCount: 310,
    soldCount: 2450,
    isTrending: true,
    isBestSeller: true,
    tags: ['Daging Sapi', 'Kentang Premium'],
    stock: 175,
    portionWeight: '85g'
  },
  {
    id: 'sb-choux-tebet',
    title: 'Japanese Vanilla Choux Craquelin',
    description: 'Kue sus modern dengan lapisan topping renyah manis dan isian diplomat cream vanilla susu segar dingin.',
    price: 8500,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Kekinian',
    kelurahanId: 'kel-tebet-barat',
    kelurahanName: 'Tebet Barat',
    rating: 4.9,
    reviewCount: 440,
    soldCount: 3300,
    isTrending: true,
    isBestSeller: true,
    tags: ['Modern Pastry', 'Cream Lumer'],
    stock: 190,
    portionWeight: '65g'
  },
  {
    id: 'sb-klepon-tebet',
    title: 'Klepon Pandan Gula Melaka Lumer',
    description: 'Bola ketan kenyal beraroma pandan alami dengan kejutan gula merah cair murni dan taburan kelapa gurih.',
    price: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-tebet-barat',
    kelurahanName: 'Tebet Barat',
    rating: 4.7,
    reviewCount: 180,
    soldCount: 1400,
    isTrending: false,
    isBestSeller: false,
    tags: ['Tradisional', 'Gula Murni'],
    stock: 210,
    portionWeight: '55g'
  },

  // ── SENAYAN ──
  {
    id: 'sb-croissant-senayan',
    title: 'Mini Butter Croissant Honey Glaze',
    description: 'Pastry Prancis berlapis renyah dengan aroma butter Prancis autentik dan olesan madu murni.',
    price: 11000,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Kekinian',
    kelurahanId: 'kel-senayan',
    kelurahanName: 'Senayan',
    rating: 4.9,
    reviewCount: 512,
    soldCount: 4100,
    isTrending: true,
    isBestSeller: true,
    tags: ['French Butter', 'Executive Snackbox'],
    stock: 150,
    portionWeight: '50g'
  },
  {
    id: 'sb-quiche-senayan',
    title: 'Mini Quiche Lorraine Smoked Chicken',
    description: 'Pai asin khas Prancis isi potongan ayam asap, keju mozarella leleh, dan custard telur rempah.',
    price: 10500,
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    category: 'Snack Gurih',
    kelurahanId: 'kel-senayan',
    kelurahanName: 'Senayan',
    rating: 4.9,
    reviewCount: 390,
    soldCount: 2800,
    isTrending: true,
    isBestSeller: false,
    tags: ['Savory Pie', 'Keju Lumer'],
    stock: 140,
    portionWeight: '75g'
  },
  {
    id: 'sb-nagasari-senayan',
    title: 'Nagasari Pisang Raja Wangi Pandan',
    description: 'Adonan tepung beras santan lembut membungkus potongan pisang raja matang manis berbalut daun pisang.',
    price: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-senayan',
    kelurahanName: 'Senayan',
    rating: 4.8,
    reviewCount: 220,
    soldCount: 1650,
    isTrending: false,
    isBestSeller: false,
    tags: ['Pisang Raja', 'Gluten Free'],
    stock: 160,
    portionWeight: '70g'
  },

  // ── KELAPA GADING TIMUR ──
  {
    id: 'sb-onde-kelapa-gading',
    title: 'Onde-Onde Wijen Isi Kacang Hijau Kupas',
    description: 'Kulit ketan kenyal empuk bertabur wijen sangrai renyah dengan pasta kacang hijau lembut legit.',
    price: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    category: 'Jajanan',
    kelurahanId: 'kel-kelapa-gading-timur',
    kelurahanName: 'Kelapa Gading Timur',
    rating: 4.8,
    reviewCount: 340,
    soldCount: 2900,
    isTrending: true,
    isBestSeller: true,
    tags: ['Wijen Sangrai', 'Padat Legit'],
    stock: 220,
    portionWeight: '60g'
  },
  {
    id: 'sb-castengel-kelapa-gading',
    title: 'Kastengel Keju Edam Belanda Renyah',
    description: 'Kue kering klasik berbahan keju Edam tua impor, gurih asin renyah lumer di mulut.',
    price: 9000,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Kering',
    kelurahanId: 'kel-kelapa-gading-timur',
    kelurahanName: 'Kelapa Gading Timur',
    rating: 4.9,
    reviewCount: 290,
    soldCount: 2200,
    isTrending: false,
    isBestSeller: true,
    tags: ['Keju Edam', 'Kue Kering'],
    stock: 130,
    portionWeight: '45g'
  },
  {
    id: 'sb-pudding-kelapa-gading',
    title: 'Silky Pudding Mango & Chia Seeds',
    description: 'Puding lembut sehalus sutra dengan puree mangga gedong asli dan topping chia seeds menyehatkan.',
    price: 8000,
    imageUrl: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    category: 'Makanan Ringan',
    kelurahanId: 'kel-kelapa-gading-timur',
    kelurahanName: 'Kelapa Gading Timur',
    rating: 4.8,
    reviewCount: 195,
    soldCount: 1540,
    isTrending: false,
    isBestSeller: false,
    tags: ['Fresh Mangga', 'Sehat'],
    stock: 140,
    portionWeight: '100g'
  },

  // ── RAWAMANGUN & LAINNYA ──
  {
    id: 'sb-arem-arem-rawamangun',
    title: 'Arem-Arem Daging Sapi Pedas Gurih',
    description: 'Nasi pulen gurih santan berbungkus daun pisang kukus dengan isian sambal goreng daging sapi mantap.',
    price: 6500,
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    category: 'Cemilan',
    kelurahanId: 'kel-rawamangun',
    kelurahanName: 'Rawamangun',
    rating: 4.8,
    reviewCount: 210,
    soldCount: 1890,
    isTrending: true,
    isBestSeller: false,
    tags: ['Kenyang', 'Pedas Gurih'],
    stock: 160,
    portionWeight: '85g'
  },
  {
    id: 'sb-bika-ambon-rawamangun',
    title: 'Bika Ambon Mini Kuning Berongga',
    description: 'Bika ambon lembut kenyal berongga sempurna dengan wangi daun jeruk dan serai segar.',
    price: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    category: 'Kue Tradisional',
    kelurahanId: 'kel-rawamangun',
    kelurahanName: 'Rawamangun',
    rating: 4.7,
    reviewCount: 175,
    soldCount: 1350,
    isTrending: false,
    isBestSeller: false,
    tags: ['Wangi Jeruk', 'Khas Nusantara'],
    stock: 140,
    portionWeight: '60g'
  }
]

export const mockDeliveryOptions: DeliveryOption[] = [
  {
    id: 'del-ekonomi',
    name: 'Ekonomi Saloka Courier',
    serviceType: 'Reguler (Tepat Waktu Acara)',
    estimate: 'Sampai sebelum jam acara (Pagi / Siang)',
    price: 15000,
    description: 'Dikirim dengan kurir motor berpendingin khusus makanan.'
  },
  {
    id: 'del-instant',
    name: 'Instant Dedicated Courier',
    serviceType: 'Langsung Antar (1-2 Jam)',
    estimate: '1-2 jam setelah pesanan siap',
    price: 28000,
    description: 'Khusus pesanan mendadak atau butuh kepastian waktu ketat.'
  },
  {
    id: 'del-van',
    name: 'Mobil Box Saloka VIP (Pesanan Besar)',
    serviceType: 'Kargo Ber-AC (>100 Box)',
    estimate: 'Sesuai jadwal pengiriman acara',
    price: 50000,
    description: 'Dilengkapi rak susun agar box snack tetap rapi dan tidak tumpuk tertindih.'
  }
]

export const mockPaymentMethods: PaymentMethodOption[] = [
  {
    id: 'pay-bca',
    name: 'BCA Virtual Account',
    code: 'BCA_VA',
    category: 'VA',
    iconText: 'BCA',
    accountNumber: '8830 1928 3482 1000'
  },
  {
    id: 'pay-mandiri',
    name: 'Mandiri Virtual Account',
    code: 'MANDIRI_VA',
    category: 'VA',
    iconText: 'MANDIRI',
    accountNumber: '8910 8823 4910 2000'
  },
  {
    id: 'pay-bri',
    name: 'BRI Virtual Account',
    code: 'BRI_VA',
    category: 'VA',
    iconText: 'BRI',
    accountNumber: '1280 4491 0284 3000'
  },
  {
    id: 'pay-qris',
    name: 'QRIS Saloka (Semua E-Wallet / Bank)',
    code: 'QRIS',
    category: 'QRIS',
    iconText: 'QRIS'
  },
  {
    id: 'pay-salokapay',
    name: 'SalokaPay Balance',
    code: 'SALOKAPAY',
    category: 'SALOKAPAY',
    iconText: 'SALOKA'
  }
]
