import crypto from 'crypto'

// Fallback Mock Data Store (In-Memory Sandbox)
export const mockUsers = [
  {
    id: 'user-admin-1',
    email: 'admin@saloka.com',
    name: 'Super Admin Saloka',
    passwordHash: crypto.createHash('sha256').update('admin2026').digest('hex'),
    role: 'ADMIN' as const,
    isSuperAdmin: true,
    latitude: -6.2088, longitude: 106.8456,
    level: 99, xp: 99999,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Super Admin', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-admin-2',
    email: 'staff@saloka.com',
    name: 'Staff Admin Saloka',
    passwordHash: crypto.createHash('sha256').update('staff2026').digest('hex'),
    role: 'ADMIN' as const,
    isSuperAdmin: false,
    latitude: -6.2088, longitude: 106.8456,
    level: 50, xp: 5000,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Admin Staff', membershipAccess: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-1',
    email: 'merchant@saloka.com',
    name: 'Kala Sourdough Studio',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.2088,
    longitude: 106.8456,
    level: 5,
    xp: 450,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"Kala Sourdough Studio","bio":"Studio Sourdough Premium Terbaik di Jakarta","phone":"08123456789","instagram":"@kalasourdough","sections":["hero","profile","products","map"]}',
    landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Distributor',
    membershipAccess: 'Diamond',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-affiliate-1',
    email: 'affiliate@saloka.com',
    name: 'Budi Affiliate Marketer',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'AFFILIATE' as const,
    latitude: -6.2200,
    longitude: 106.8500,
    level: 3,
    xp: 250,
    landingPageTemplate: null,
    landingPageConfig: null,
    landingPageSetup: false,
    parentAffiliateId: null,
    membershipLevel: 'Agen',
    membershipAccess: 'Platinum',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-customer-1',
    email: 'customer@saloka.com',
    name: 'Andi Pembeli',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'CUSTOMER' as const,
    latitude: -6.2000,
    longitude: 106.8300,
    level: 1,
    xp: 20,
    landingPageTemplate: null,
    landingPageConfig: null,
    landingPageSetup: false,
    parentAffiliateId: 'user-affiliate-1',
    membershipLevel: 'Reseller',
    membershipAccess: 'Gold',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-cs-1',
    email: 'cs@saloka.com',
    name: 'Budi Customer Service',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'CUSTOMER_SERVICE' as const,
    latitude: -6.2000,
    longitude: 106.8300,
    level: 1,
    xp: 0,
    landingPageTemplate: null,
    landingPageConfig: null,
    landingPageSetup: false,
    parentAffiliateId: null,
    membershipLevel: 'Staff',
    membershipAccess: 'Gold',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ─── Additional Mock Merchants ───────────────────────────────────────────────
  {
    id: 'user-merchant-2',
    email: 'nusantara.fashion@saloka.com',
    name: 'Nusantara Fashion House',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -7.7972,
    longitude: 110.3688,
    level: 4,
    xp: 380,
    landingPageTemplate: 'neo-brutalism',
    landingPageConfig: '{"title":"Nusantara Fashion House","bio":"Batik & fashion lokal premium dari Jogja","phone":"08567890123","instagram":"@nusantarafashion"}',
    landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Agen',
    membershipAccess: 'Diamond',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-merchant-3',
    email: 'techgeek.id@saloka.com',
    name: 'TechGeek Indonesia',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.1751,
    longitude: 106.8650,
    level: 6,
    xp: 600,
    landingPageTemplate: 'glassmorphism',
    landingPageConfig: '{"title":"TechGeek Indonesia","bio":"Gadget & aksesoris teknologi terpercaya","phone":"08789012345","instagram":"@techgeek.id"}',
    landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Distributor',
    membershipAccess: 'Diamond',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-merchant-4',
    email: 'dapur.kreatif@saloka.com',
    name: 'Dapur Kreatif Nusantara',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -7.2504,
    longitude: 112.7688,
    level: 3,
    xp: 290,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"Dapur Kreatif Nusantara","bio":"Makanan & minuman artisan pilihan dari Surabaya","phone":"08234567890","instagram":"@dapurkreatif"}',
    landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Reseller',
    membershipAccess: 'Platinum',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-merchant-5',
    email: 'kreasi.digital@saloka.com',
    name: 'Kreasi Digital Studio',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -8.4095,
    longitude: 115.1889,
    level: 7,
    xp: 720,
    landingPageTemplate: 'glassmorphism',
    landingPageConfig: '{"title":"Kreasi Digital Studio","bio":"Jasa desain, foto, video & IT profesional dari Bali","phone":"08345678901","instagram":"@kreasidigital"}',
    landingPageSetup: true,
    parentAffiliateId: null,
    membershipLevel: 'Distributor',
    membershipAccess: 'Diamond',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ─── 10 New Business Users ────────────────────────────────────────────────────
  {
    id: 'user-merchant-6',
    email: 'herbal.nusantara@saloka.com',
    name: 'Herbal Nusantara Apotik',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.9147, longitude: 107.6098,
    level: 4, xp: 360,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"Herbal Nusantara","bio":"Produk herbal dan kesehatan alami pilihan dari Bandung","phone":"08111222333","instagram":"@herbalnusantara"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Agen', membershipAccess: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-7',
    email: 'furni.jepara@saloka.com',
    name: 'Furnicraft Jepara',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.5896, longitude: 110.6688,
    level: 5, xp: 480,
    landingPageTemplate: 'neo-brutalism',
    landingPageConfig: '{"title":"Furnicraft Jepara","bio":"Furniture kayu jati ukir premium langsung dari pengrajin Jepara","phone":"08222333444","instagram":"@furnicraftjepara"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Distributor', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-8',
    email: 'agro.segar@saloka.com',
    name: 'AgroSegar Farm Bogor',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.5971, longitude: 106.8060,
    level: 3, xp: 210,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"AgroSegar Farm","bio":"Sayur & buah organik segar dari kebun sendiri di Bogor","phone":"08333444555","instagram":"@agrosegar"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Reseller', membershipAccess: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-9',
    email: 'aksesoris.silver@saloka.com',
    name: 'Silver Artisan Celuk',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -8.5833, longitude: 115.2667,
    level: 6, xp: 550,
    landingPageTemplate: 'glassmorphism',
    landingPageConfig: '{"title":"Silver Artisan Celuk","bio":"Perhiasan perak handmade asli pengrajin Celuk Bali","phone":"08444555666","instagram":"@silverceluk"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Agen', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-10',
    email: 'konveksi.solo@saloka.com',
    name: 'Konveksi Solo Premium',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -7.5755, longitude: 110.8243,
    level: 4, xp: 420,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"Konveksi Solo Premium","bio":"Produksi seragam, kaos, dan jaket sablon berkualitas dari Solo","phone":"08555666777","instagram":"@konveksisolo"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Agen', membershipAccess: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-11',
    email: 'edu.kids@saloka.com',
    name: 'EduKids Toy Studio',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -7.2575, longitude: 112.7521,
    level: 3, xp: 280,
    landingPageTemplate: 'neo-brutalism',
    landingPageConfig: '{"title":"EduKids Toy Studio","bio":"Mainan edukasi anak ramah lingkungan buatan lokal Surabaya","phone":"08666777888","instagram":"@edukidstoy"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Reseller', membershipAccess: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-12',
    email: 'skincare.lokal@saloka.com',
    name: 'Glow Local Skincare',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.2146, longitude: 106.8451,
    level: 5, xp: 510,
    landingPageTemplate: 'glassmorphism',
    landingPageConfig: '{"title":"Glow Local Skincare","bio":"Skincare natural berbahan baku lokal Indonesia, BPOM terdaftar","phone":"08777888999","instagram":"@glowlocal"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Distributor', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-13',
    email: 'pet.care.id@saloka.com',
    name: 'PetCare Indonesia',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.1944, longitude: 106.8229,
    level: 3, xp: 230,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"PetCare Indonesia","bio":"Produk & layanan perawatan hewan peliharaan terpercaya Jakarta","phone":"08888999000","instagram":"@petcareid"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Reseller', membershipAccess: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-14',
    email: 'properti.kost@saloka.com',
    name: 'Kost Premium Menteng',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -6.1862, longitude: 106.8355,
    level: 4, xp: 350,
    landingPageTemplate: 'modern-gold',
    landingPageConfig: '{"title":"Kost Premium Menteng","bio":"Kost eksklusif dan jasa properti di kawasan Menteng Jakarta","phone":"08999000111","instagram":"@kostmenteng"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Agen', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-merchant-15',
    email: 'otomotif.bengkel@saloka.com',
    name: 'Bengkel Pro Autocare',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'MERCHANT' as const,
    latitude: -7.2830, longitude: 112.7372,
    level: 5, xp: 470,
    landingPageTemplate: 'neo-brutalism',
    landingPageConfig: '{"title":"Bengkel Pro Autocare","bio":"Servis dan aksesoris kendaraan roda dua & empat Surabaya","phone":"08000111222","instagram":"@bengkelproauto"}',
    landingPageSetup: true, parentAffiliateId: null,
    membershipLevel: 'Distributor', membershipAccess: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-affiliate-2',
    email: 'affiliate2@saloka.com',
    name: 'Siti Affiliate Marketer',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'AFFILIATE' as const,
    latitude: -6.2300, longitude: 106.8600,
    level: 2, xp: 150,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: false,
    parentAffiliateId: 'user-affiliate-1',
    membershipLevel: 'Reseller', membershipAccess: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-affiliate-3',
    email: 'affiliate3@saloka.com',
    name: 'Bambang Sub-Affiliate',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'AFFILIATE' as const,
    latitude: -6.2400, longitude: 106.8700,
    level: 1, xp: 50,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: false,
    parentAffiliateId: 'user-affiliate-2',
    membershipLevel: 'Agen', membershipAccess: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-customer-2',
    email: 'customer2@saloka.com',
    name: 'Joko Pembeli',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'CUSTOMER' as const,
    latitude: -6.2500, longitude: 106.8800,
    level: 1, xp: 10,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: false,
    parentAffiliateId: 'user-affiliate-2',
    membershipLevel: 'Reseller', membershipAccess: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'user-customer-3',
    email: 'customer3@saloka.com',
    name: 'Dewi Pembeli',
    passwordHash: crypto.createHash('sha256').update('password123').digest('hex'),
    role: 'CUSTOMER' as const,
    latitude: -6.2600, longitude: 106.8900,
    level: 1, xp: 5,
    landingPageTemplate: null, landingPageConfig: null, landingPageSetup: false,
    parentAffiliateId: 'user-affiliate-3',
    membershipLevel: 'Reseller', membershipAccess: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
]

export const mockProducts = [
  // ─── TOKO & RITEL ────────────────────────────────────────────────────────────
  {
    id: 'prod-gayo-coffee',
    title: 'Kopi Gayo Organik Premium',
    description: 'Kopi gayo organik dengan proses honey, menghadirkan rasa fruity yang segar dengan body tebal yang lembut.',
    price: 150000,
    category: 'TOKO' as const,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    isAffiliateEnabled: true,
    affiliateCommissionType: 'PERCENT',
    affiliateCommissionValue: 5.0,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-batik-lurik',
    title: 'Batik Lurik Premium Jogja',
    description: 'Kain batik lurik tenun tangan asli Jogjakarta, motif klasik dengan warna natural yang elegan.',
    price: 285000,
    category: 'PAKAIAN_PRIA' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── KAFE & KULINER ──────────────────────────────────────────────────────────
  {
    id: 'prod-sourdough',
    title: 'Artisan Country Sourdough',
    description: 'Roti sourdough klasik berpori besar dengan kulit renyah (crust) dan rasa asam khas ragi alami.',
    price: 65000,
    category: 'KAFE' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc7b?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-cold-brew',
    title: 'Cold Brew Coffee Botolan 500ml',
    description: 'Cold brew 18 jam dengan single origin Ethiopia Yirgacheffe. Cocok untuk coffee shop dan reseller.',
    price: 45000,
    category: 'MAKANAN_MINUMAN' as const,
    stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2145, longitude: 106.8272,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-sambal-artisan',
    title: 'Sambal Bajak Artisan Medan',
    description: 'Sambal bajak dengan cabe rawit lokal pilihan, dimasak tradisional tanpa MSG, tahan 2 bulan.',
    price: 38000,
    category: 'MAKANAN_MINUMAN' as const,
    stock: 75,
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: 3.5952, longitude: 98.6722,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── ELEKTRONIK ──────────────────────────────────────────────────────────────
  {
    id: 'prod-earphone-tws',
    title: 'TWS Earbuds Wireless ANC Pro',
    description: 'True wireless earbuds dengan Active Noise Cancellation, Bluetooth 5.3, baterai 30 jam, IPX5 waterproof.',
    price: 299000,
    category: 'ELEKTRONIK' as const,
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-powerbank-65w',
    title: 'Powerbank 20.000mAh 65W GaN',
    description: 'Powerbank GaN 65W dengan 3 port (USB-C PD + 2 USB-A), support fast charging laptop dan ponsel.',
    price: 449000,
    category: 'ELEKTRONIK' as const,
    stock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2349, longitude: 106.9896,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── HANDPHONE & AKSESORIS ───────────────────────────────────────────────────
  {
    id: 'prod-case-magsafe',
    title: 'Case iPhone MagSafe Premium Leather',
    description: 'Casing iPhone full leather Italy dengan slot kartu dan ring holder, compatible MagSafe semua seri.',
    price: 189000,
    category: 'HANDPHONE_AKSESORIS' as const,
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.1944, longitude: 106.8229,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── KOMPUTER & AKSESORIS ────────────────────────────────────────────────────
  {
    id: 'prod-mouse-ergonomic',
    title: 'Mouse Ergonomik Wireless 4K DPI',
    description: 'Mouse vertikal ergonomik wireless 2.4G + Bluetooth dual mode, DPI 400-4000, baterai 90 hari.',
    price: 235000,
    category: 'KOMPUTER_AKSESORIS' as const,
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2480, longitude: 106.7850,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-keyboard-mechanical',
    title: 'Keyboard Mekanikal 75% RGB Hotswap',
    description: 'Keyboard 75% layout, hot-swappable switch, backlight RGB per-key, gasket mount anti-bounce.',
    price: 850000,
    category: 'KOMPUTER_AKSESORIS' as const,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── PERAWATAN & KECANTIKAN ──────────────────────────────────────────────────
  {
    id: 'prod-serum-vitamin-c',
    title: 'Serum Vitamin C 20% Brightening',
    description: 'Serum wajah Vitamin C 20% + Niacinamide 5%, mencerahkan flek hitam, dermatologically tested.',
    price: 175000,
    category: 'PERAWATAN_KECANTIKAN' as const,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.1951, longitude: 106.8309,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-masker-matcha',
    title: 'Clay Mask Matcha & Charcoal',
    description: 'Masker tanah liat dengan matcha Jepang dan charcoal aktif, membersihkan pori dan mengontrol minyak.',
    price: 89000,
    category: 'PERAWATAN_KECANTIKAN' as const,
    stock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── PERLENGKAPAN RUMAH ──────────────────────────────────────────────────────
  {
    id: 'prod-lilin-aromaterapi',
    title: 'Lilin Aromaterapi Soy Wax Vanilla',
    description: 'Lilin kedelai (soy wax) aromaterapi vanilla & sandalwood, burn time 55 jam, handcrafted Bali.',
    price: 125000,
    category: 'PERLENGKAPAN_RUMAH' as const,
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-organizer-anyaman',
    title: 'Keranjang Organizer Anyaman Rotan',
    description: 'Keranjang serbaguna dari rotan alam pilihan, bisa digunakan untuk pakaian, mainan, atau dekorasi.',
    price: 145000,
    category: 'PERLENGKAPAN_RUMAH' as const,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── PAKAIAN WANITA ──────────────────────────────────────────────────────────
  {
    id: 'prod-dress-linen',
    title: 'Dress Linen Premium Midi Cut',
    description: 'Dress linen natural breathable midi cut, cocok untuk casual dan formal, tersedia 8 pilihan warna.',
    price: 325000,
    category: 'PAKAIAN_WANITA' as const,
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2318, longitude: 106.8243,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── FASHION MUSLIM ──────────────────────────────────────────────────────────
  {
    id: 'prod-gamis-syari',
    title: 'Gamis Syari Premium Wolfis',
    description: 'Gamis wolly crepe syari modern, jahitan rapi, tersedia ukuran S-3XL dan 10+ pilihan warna muda.',
    price: 285000,
    category: 'FASHION_MUSLIM' as const,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b984d?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── SEPATU PRIA ─────────────────────────────────────────────────────────────
  {
    id: 'prod-sneaker-lokal',
    title: 'Sneaker Casual Kulit Lokal Bandung',
    description: 'Sepatu kulit sapi asli Bandung, sole rubber anti-slip, tersedia ukuran 38-44, handmade artisan.',
    price: 465000,
    category: 'SEPATU_PRIA' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.9175, longitude: 107.6191,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── SEPATU WANITA ────────────────────────────────────────────────────────────
  {
    id: 'prod-flat-shoes',
    title: 'Flat Shoes Kulit Ular Python Motif',
    description: 'Sepatu flat wanita dengan bahan PU kulit motif python, ringan dan elegan untuk segala outfit.',
    price: 195000,
    category: 'SEPATU_WANITA' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2318, longitude: 106.8243,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── KESEHATAN ───────────────────────────────────────────────────────────────
  {
    id: 'prod-madu-hutan',
    title: 'Madu Hutan Kalimantan Pure Raw',
    description: 'Madu hutan liar murni tanpa campuran dari lebah Apis dorsata Kalimantan, kaya enzim dan antioksidan.',
    price: 195000,
    category: 'KESEHATAN' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: 0.5388, longitude: 116.4194,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-suplemen-herbal',
    title: 'Kapsul Temulawak + Jahe Merah Organik',
    description: 'Suplemen herbal temulawak dan jahe merah organik, 60 kapsul, meningkatkan imunitas dan stamina.',
    price: 85000,
    category: 'KESEHATAN' as const,
    stock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1612197527762-8cfb4b634b73?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── HOBI & KOLEKSI ──────────────────────────────────────────────────────────
  {
    id: 'prod-miniatur-gundam',
    title: 'Gundam HG 1/144 Barbatos Lupus',
    description: 'Model kit Gundam HG 1:144 Iron Blooded Orphans series, lengkap dengan runner dan stiker detail.',
    price: 350000,
    category: 'HOBI_KOLEKSI' as const,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1608306448197-e83633f1261c?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── OLAHRAGA & OUTDOOR ──────────────────────────────────────────────────────
  {
    id: 'prod-carabiner-set',
    title: 'Carabiner Set Climbing CE Certified',
    description: 'Set carabiner aluminum alloy CE certified, kapasitas 22kN, untuk panjat tebing dan outdoor adventure.',
    price: 185000,
    category: 'OLAHRAGA_OUTDOOR' as const,
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.9175, longitude: 107.6191,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-yoga-mat',
    title: 'Yoga Mat NBR 10mm Anti-Slip Premium',
    description: 'Matras yoga NBR foam tebal 10mm, panjang 183cm, dengan tali pengait dan tas jinjing gratis.',
    price: 145000,
    category: 'OLAHRAGA_OUTDOOR' as const,
    stock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── OTOMOTIF ─────────────────────────────────────────────────────────────────
  {
    id: 'prod-wax-carnauba',
    title: 'Carnauba Wax Premium Detailing',
    description: 'Carnauba wax murni konsentrasi tinggi untuk detailing mobil, memberikan kilap deep gloss tahan 6 bulan.',
    price: 285000,
    category: 'OTOMOTIF' as const,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── BUKU & ALAT TULIS ───────────────────────────────────────────────────────
  {
    id: 'prod-jurnal-kulit',
    title: 'Jurnal Kulit Asli A5 Handmade Bali',
    description: 'Buku jurnal kulit sapi asli A5 handmade Bali, 200 halaman dotted, tersedia dalam 6 warna pilihan.',
    price: 225000,
    category: 'BUKU_ALAT_TULIS' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── TAS WANITA ──────────────────────────────────────────────────────────────
  {
    id: 'prod-tote-canvas',
    title: 'Tote Bag Canvas Premium Motif Wayang',
    description: 'Totebag kanvas tebal 16oz dengan motif wayang batik eksklusif, ukuran jumbo A4, inner pocket.',
    price: 155000,
    category: 'TAS_WANITA' as const,
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── FOTOGRAFI ───────────────────────────────────────────────────────────────
  {
    id: 'prod-filter-nd',
    title: 'Filter ND Variable 67mm ND2-ND400',
    description: 'Filter ND variabel 67mm, optical glass multi-coated, cocok untuk video cinematic dan landscape.',
    price: 245000,
    category: 'FOTOGRAFI' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── VOUCHER ─────────────────────────────────────────────────────────────────
  {
    id: 'prod-voucher-kopi',
    title: 'Voucher Minuman Kopi 10x Prepaid',
    description: 'Voucher minum kopi 10x di jaringan Saloka Coffee, berlaku 90 hari, bisa digunakan untuk semua varian.',
    price: 120000,
    category: 'VOUCHER' as const,
    stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── DEALS SEKITAR ───────────────────────────────────────────────────────────
  {
    id: 'prod-deal-bakso',
    title: 'Promo Bakso Premium Pak Slamet 2 Porsi',
    description: 'Dapatkan 2 porsi bakso premium urat + sumsum Pak Slamet dengan harga spesial, hanya di Saloka.id.',
    price: 32000,
    category: 'DEALS_SEKITAR' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.9175, longitude: 107.6191,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── JASA & LAYANAN ──────────────────────────────────────────────────────────
  {
    id: 'prod-branding-service',
    title: 'Jasa Desain Branding UMKM Full Package',
    description: 'Paket desain identitas visual lengkap: logo, brosur, kemasan, dan media sosial template.',
    price: 1500000,
    category: 'JASA' as const,
    stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2200, longitude: 106.8500,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-foto-produk',
    title: 'Jasa Fotografi Produk 20 Foto Studio',
    description: 'Sesi pemotretan produk di studio profesional, 20 foto editing clean background, ready social media.',
    price: 350000,
    category: 'JASA' as const,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  // ─── LOWONGAN KERJA ──────────────────────────────────────────────────────────
  {
    id: 'prod-loker-admin',
    title: '[LOKER] Admin Marketplace Freelance WFH',
    description: 'Dibutuhkan admin toko online freelance WFH, pengalaman Tokopedia/Shopee diutamakan, fee per project.',
    price: 0,
    category: 'KERJAAN' as const,
    stock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.2088, longitude: 106.8456,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-loker-kurir',
    title: '[LOKER] Driver Kurir Motor Harian Bandung',
    description: 'Butuh driver kurir motor area Bandung kota, jam kerja fleksibel, gaji harian + bonus pengiriman.',
    price: 0,
    category: 'KERJAAN' as const,
    stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400&q=80',
    merchantId: 'user-merchant-1',
    latitude: -6.9175, longitude: 107.6191,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK DARI MERCHANT-2 (Nusantara Fashion House) ────────────────────────
  {
    id: 'prod-batik-tulis-premium',
    title: 'Batik Tulis Sutra Premium Jogja',
    description: 'Batik tulis tangan asli Jogjakarta menggunakan bahan sutra murni. Motif parang rusak, semen, atau sesuai pesanan. Proses 3-4 minggu.',
    price: 1850000,
    category: 'PAKAIAN_PRIA' as const,
    stock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&q=80',
    merchantId: 'user-merchant-2',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-kebaya-modern',
    title: 'Kebaya Modern Brokat Premium Set',
    description: 'Kebaya modern bahan brokat Prancis dengan rok satin. Tersedia warna pastel dan bold, ukuran XS-3XL, bisa custom.',
    price: 750000,
    category: 'PAKAIAN_WANITA' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b984d?w=400&q=80',
    merchantId: 'user-merchant-2',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-tenun-ntt',
    title: 'Kain Tenun Ikat NTT Asli Motif Sumba',
    description: 'Kain tenun ikat tangan asli dari Sumba Barat, motif kuda dan mamuli tradisional. 1 lembar kain ukuran 200x70cm.',
    price: 650000,
    category: 'TOKO' as const,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    merchantId: 'user-merchant-2',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-tas-anyam-rotan',
    title: 'Tas Anyam Rotan Handmade Premium',
    description: 'Tas wanita anyaman rotan alam pilihan, finishing natural oil, ukuran medium 30x25cm, dengan tali kulit.',
    price: 385000,
    category: 'TAS_WANITA' as const,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    merchantId: 'user-merchant-2',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-jahit-custom',
    title: 'Jasa Jahit Baju Custom & Alterasi',
    description: 'Jasa jahit pakaian custom dari kain Anda sendiri atau bahan kami. Termasuk kemeja, gaun, jas, dan seragam. Pengerjaan 7-14 hari.',
    price: 350000,
    category: 'JASA' as const,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80',
    merchantId: 'user-merchant-2',
    latitude: -7.7972, longitude: 110.3688,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK DARI MERCHANT-3 (TechGeek Indonesia) ─────────────────────────────
  {
    id: 'prod-smartwatch-garmin',
    title: 'Smartwatch GPS Running Premium',
    description: 'Smartwatch GPS dengan sensor HR 24/7, SpO2, stress tracking, baterai 14 hari, waterproof 5ATM. Cocok untuk pelari dan atlet.',
    price: 2950000,
    category: 'ELEKTRONIK' as const,
    stock: 12,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-laptop-stand',
    title: 'Laptop Stand Aluminium Adjustable Pro',
    description: 'Stand laptop aluminium dengan 6 tingkat ketinggian, foldable ultra-tipis, kompatibel 11-17 inch, anti-slip silicone pad.',
    price: 185000,
    category: 'KOMPUTER_AKSESORIS' as const,
    stock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-webcam-4k',
    title: 'Webcam 4K UHD Auto-Focus Ring Light Built-in',
    description: 'Webcam 4K 60fps dengan auto-focus AI, ring light built-in 3 mode warna, microphone noise-cancelling. Plug & play USB-C.',
    price: 785000,
    category: 'KOMPUTER_AKSESORIS' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-servis-hp',
    title: 'Jasa Servis HP & Tablet All Brand',
    description: 'Servis HP dan tablet semua merek: ganti LCD, baterai, IC, board rusak. Bergaransi 30 hari. Antar jemput area Jakarta.',
    price: 125000,
    category: 'JASA' as const,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-it-support',
    title: 'Jasa IT Support & Maintenance Bisnis',
    description: 'Layanan IT support bulanan untuk bisnis: setup jaringan, install software, backup data, troubleshoot. Remote & on-site Jakarta-Depok.',
    price: 750000,
    category: 'JASA' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-setup-toko-online',
    title: 'Jasa Setup Toko Online Tokopedia/Shopee',
    description: 'Setup toko online lengkap: buat akun, optimasi profil, upload 20 produk dengan foto & deskripsi SEO, setting pengiriman & pembayaran.',
    price: 450000,
    category: 'JASA' as const,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&q=80',
    merchantId: 'user-merchant-3',
    latitude: -6.1751, longitude: 106.8650,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK DARI MERCHANT-4 (Dapur Kreatif Nusantara) ────────────────────────
  {
    id: 'prod-rendang-premium',
    title: 'Rendang Daging Sapi Premium Padang 500g',
    description: 'Rendang daging sapi murni khas Padang, dimasak 8 jam dengan rempah pilihan, tahan 1 bulan tanpa kulkas. Halal MUI.',
    price: 125000,
    category: 'MAKANAN_MINUMAN' as const,
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80',
    merchantId: 'user-merchant-4',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-keripik-tempe',
    title: 'Keripik Tempe Malang Renyah 250g',
    description: 'Keripik tempe khas Malang, dibuat dari tempe murni pilihan, 4 varian rasa: original, BBQ, balado, keju. Tanpa pengawet.',
    price: 28000,
    category: 'MAKANAN_MINUMAN' as const,
    stock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80',
    merchantId: 'user-merchant-4',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-kopi-toraja',
    title: 'Kopi Arabika Toraja Sapan 200g Whole Bean',
    description: 'Kopi Arabika Toraja Sapan single origin, proses natural, dipetik tangan. Profil rasa: dark chocolate, caramel, fruity finish.',
    price: 98000,
    category: 'MAKANAN_MINUMAN' as const,
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80',
    merchantId: 'user-merchant-4',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-catering',
    title: 'Jasa Catering Prasmanan 50-200 Pax',
    description: 'Paket catering prasmanan untuk acara kantor, pernikahan, dan ulang tahun. Menu masakan Jawa, Sunda, dan Padang. Include peralatan makan.',
    price: 85000,
    category: 'JASA' as const,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=400&q=80',
    merchantId: 'user-merchant-4',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-kue-custom',
    title: 'Jasa Kue Custom & Wedding Cake',
    description: 'Custom cake untuk ulang tahun, wedding, baby shower. Bahan premium, fondant atau buttercream. Konsultasi desain gratis. Min order 5 hari sebelum acara.',
    price: 450000,
    category: 'JASA' as const,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80',
    merchantId: 'user-merchant-4',
    latitude: -7.2504, longitude: 112.7688,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK DARI MERCHANT-5 (Kreasi Digital Studio) ─────────────────────────
  {
    id: 'prod-jasa-desain-logo',
    title: 'Jasa Desain Logo Profesional + Guideline',
    description: 'Desain logo profesional dengan 3 konsep awal, revisi unlimited, file AI/EPS/PNG/PDF, plus brand guideline warna & tipografi. Pengerjaan 5-7 hari.',
    price: 850000,
    category: 'JASA' as const,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-foto-produk-bali',
    title: 'Jasa Foto Produk Profesional Studio Bali',
    description: 'Sesi foto produk di studio profesional Bali: 30 foto editan clean background atau lifestyle. Termasuk video pendek 15 detik untuk Reels/TikTok.',
    price: 750000,
    category: 'JASA' as const,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-kelola-sosmed',
    title: 'Jasa Kelola Media Sosial UMKM (1 Bulan)',
    description: 'Paket kelola Instagram + TikTok 1 bulan: 20 konten/bulan, copywriting, edit foto/video, schedule posting, reply komentar & DM.',
    price: 1500000,
    category: 'JASA' as const,
    stock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-video-iklan',
    title: 'Jasa Produksi Video Iklan 60 Detik',
    description: 'Video iklan profesional 60 detik: script, shooting, editing, motion graphic, colour grading. Cocok untuk FB Ads, IG Ads, dan TikTok Ads.',
    price: 2500000,
    category: 'JASA' as const,
    stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-website-umkm',
    title: 'Jasa Buat Website Toko Online UMKM',
    description: 'Website toko online profesional: domain + hosting 1 tahun, desain premium, katalog produk, form order WhatsApp, SEO dasar. Selesai 14 hari.',
    price: 3500000,
    category: 'JASA' as const,
    stock: 6,
    imageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-ads-management',
    title: 'Jasa Kelola Meta Ads & Google Ads (1 Bulan)',
    description: 'Kelola iklan Facebook, Instagram, dan Google Ads: riset audience, buat campaign, A/B testing kreatif, optimasi harian, laporan mingguan.',
    price: 2000000,
    category: 'JASA' as const,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-preset-lightroom',
    title: 'Preset Lightroom Premium Pack 50 Filter',
    description: 'Bundle 50 preset Lightroom professional: moody, bright airy, vintage, dark, dan food photography. Cocok untuk HP dan desktop.',
    price: 75000,
    category: 'FOTOGRAFI' as const,
    stock: 999,
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&q=80',
    merchantId: 'user-merchant-5',
    latitude: -8.4095, longitude: 115.1889,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-6 (Herbal Nusantara) ────────────────────────────
  {
    id: 'prod-madu-hitam',
    title: 'Madu Hitam Pahit Kalimantan 250ml',
    description: 'Madu hitam pahit asli Kalimantan, kaya antioksidan, proses cold extraction tanpa pemanas. Berkhasiat untuk imunitas dan stamina. Sertifikat uji lab tersedia.',
    price: 185000, category: 'KESEHATAN' as const, stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=400&q=80',
    merchantId: 'user-merchant-6', latitude: -6.9147, longitude: 107.6098,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-teh-herbal',
    title: 'Teh Herbal Racikan Jamu Premium 30 Sachet',
    description: 'Racikan teh herbal dari 12 tanaman rempah pilihan: jahe merah, kayu manis, cengkeh, dll. Untuk kesehatan pencernaan dan daya tahan tubuh.',
    price: 75000, category: 'KESEHATAN' as const, stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80',
    merchantId: 'user-merchant-6', latitude: -6.9147, longitude: 107.6098,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-konsultasi-herbal',
    title: 'Jasa Konsultasi Herbal & Ramuan Tradisional Online',
    description: 'Konsultasi kesehatan dengan herbalis berpengalaman via WhatsApp/Zoom, termasuk rekomendasi tanaman herbal dan cara pemakaian yang tepat. Durasi 45 menit.',
    price: 150000, category: 'JASA' as const, stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&q=80',
    merchantId: 'user-merchant-6', latitude: -6.9147, longitude: 107.6098,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-7 (Furnicraft Jepara) ───────────────────────────
  {
    id: 'prod-kursi-ukir-jepara',
    title: 'Kursi Tamu Ukir Jepara Set 3+1+1',
    description: 'Set kursi tamu kayu jati ukir Jepara, motif bunga klasik, finishing melamine glossy. Set terdiri dari: sofa 3 dudukan + 2 sofa 1 dudukan. Custom warna & motif.',
    price: 8500000, category: 'PERLENGKAPAN_RUMAH' as const, stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    merchantId: 'user-merchant-7', latitude: -6.5896, longitude: 110.6688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-meja-makan-jati',
    title: 'Meja Makan Minimalis Kayu Jati 6 Kursi',
    description: 'Meja makan kayu jati solid minimalis modern, ukuran 180x90cm, finishing natural oil. Include 6 kursi makan. Pengiriman dalam Pulau Jawa gratis.',
    price: 6200000, category: 'PERLENGKAPAN_RUMAH' as const, stock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400&q=80',
    merchantId: 'user-merchant-7', latitude: -6.5896, longitude: 110.6688,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-custom-furniture',
    title: 'Jasa Custom Furniture Kayu Jati (by Order)',
    description: 'Pembuatan furniture kayu jati custom sesuai desain dan ukuran Anda: lemari, bufet, meja, rak, dll. Konsultasi desain gratis, estimasi harga dalam 24 jam.',
    price: 2500000, category: 'JASA' as const, stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80',
    merchantId: 'user-merchant-7', latitude: -6.5896, longitude: 110.6688,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-8 (AgroSegar Farm) ──────────────────────────────
  {
    id: 'prod-sayur-organik-box',
    title: 'Box Sayur Organik Mingguan 5kg',
    description: 'Paket sayur organik segar langsung dari kebun: bayam, kangkung, wortel, brokoli, tomat cherry, dll. Panen hari H, antar ke rumah Jabodetabek. Subscribe mingguan diskon 15%.',
    price: 95000, category: 'MAKANAN_MINUMAN' as const, stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80',
    merchantId: 'user-merchant-8', latitude: -6.5971, longitude: 106.8060,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-bibit-sayur',
    title: 'Paket Bibit Sayur Organik 10 Jenis',
    description: 'Paket bibit sayur organik non-GMO: selada, kangkung, bayam merah, pakcoy, kale, tomat, cabai, terong, timun, labu. Cocok untuk urban farming dan hidroponik.',
    price: 65000, category: 'MAKANAN_MINUMAN' as const, stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    merchantId: 'user-merchant-8', latitude: -6.5971, longitude: 106.8060,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-urban-farming',
    title: 'Jasa Setup Urban Farming & Hidroponik Rumah',
    description: 'Setup sistem hidroponik di rumah atau kantor: NFT, DFT, atau wick system. Include instalasi, media tanam, nutrisi awal, dan pelatihan perawatan. Bergaransi 1 bulan.',
    price: 1800000, category: 'JASA' as const, stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80',
    merchantId: 'user-merchant-8', latitude: -6.5971, longitude: 106.8060,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-9 (Silver Artisan Celuk) ───────────────────────
  {
    id: 'prod-gelang-perak-bali',
    title: 'Gelang Perak Bali Motif Ukir 925 Sterling',
    description: 'Gelang perak murni 925 sterling silver handmade pengrajin Celuk Bali. Motif ukir bunga & daun tradisional. Tersedia ukuran 16-20cm, dengan box packaging premium.',
    price: 385000, category: 'AKSESORIS_FASHION' as const, stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-9519f94816f0?w=400&q=80',
    merchantId: 'user-merchant-9', latitude: -8.5833, longitude: 115.2667,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-kalung-perak-natural',
    title: 'Kalung Perak Natural Stone Moonstone',
    description: 'Kalung perak 925 dengan liontin batu moonstone asli, handmade artisan Bali. Panjang rantai 45cm adjustable. Tersedia dalam box kayu berukir.',
    price: 550000, category: 'AKSESORIS_FASHION' as const, stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80',
    merchantId: 'user-merchant-9', latitude: -8.5833, longitude: 115.2667,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-custom-perhiasan',
    title: 'Jasa Custom Perhiasan Perak (Wedding & Special)',
    description: 'Custom cincin tunangan, cincin nikah, atau perhiasan spesial lainnya dari perak 925. Desain sesuai keinginan, proses 7-14 hari. Sertifikat keaslian tersedia.',
    price: 850000, category: 'JASA' as const, stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&q=80',
    merchantId: 'user-merchant-9', latitude: -8.5833, longitude: 115.2667,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-10 (Konveksi Solo) ──────────────────────────────
  {
    id: 'prod-kaos-polo-sablon',
    title: 'Kaos Polo Custom Sablon DTF Min 12pcs',
    description: 'Kaos polo cotton combed 30s, sablon DTF full color tahan lama. Min order 12pcs, bisa beda ukuran dalam 1 order. Pengerjaan 5-7 hari kerja.',
    price: 85000, category: 'PAKAIAN_PRIA' as const, stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&q=80',
    merchantId: 'user-merchant-10', latitude: -7.5755, longitude: 110.8243,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jaket-hoodie-custom',
    title: 'Jaket Hoodie Fleece Custom Logo Min 6pcs',
    description: 'Hoodie fleece premium 280gsm, bordir atau sablon logo sesuai permintaan. Tersedia warna hitam, navy, abu-abu. Min 6pcs, beda ukuran S-3XL OK.',
    price: 165000, category: 'PAKAIAN_PRIA' as const, stock: 150,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80',
    merchantId: 'user-merchant-10', latitude: -7.5755, longitude: 110.8243,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-seragam-perusahaan',
    title: 'Jasa Produksi Seragam Perusahaan & Instansi',
    description: 'Produksi seragam kantor, sekolah, dan instansi pemerintah: kemeja, kaos, jaket, rompi. Bisa bordir logo, cetak nama, dan nomor punggung. Min 20pcs. Konsultasi gratis.',
    price: 95000, category: 'JASA' as const, stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    merchantId: 'user-merchant-10', latitude: -7.5755, longitude: 110.8243,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-11 (EduKids Toy Studio) ────────────────────────
  {
    id: 'prod-puzzle-kayu-edukasi',
    title: 'Puzzle Kayu Edukasi Peta Indonesia',
    description: 'Puzzle kayu premium berbentuk peta Indonesia, 34 provinsi warna-warni, cat food-grade non-toxic, aman untuk anak 3+. Include buku panduan dan flashcard provinsi.',
    price: 145000, category: 'HOBI_KOLEKSI' as const, stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&q=80',
    merchantId: 'user-merchant-11', latitude: -7.2575, longitude: 112.7521,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-balok-bangunan-kayu',
    title: 'Set Balok Bangunan Kayu 100 Pcs STEM',
    description: 'Set 100 balok bangunan kayu natural dari kayu mahoni, aneka bentuk geometri. Mendukung perkembangan motorik dan kreativitas anak. Ramah lingkungan, tanpa cat.',
    price: 195000, category: 'HOBI_KOLEKSI' as const, stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=80',
    merchantId: 'user-merchant-11', latitude: -7.2575, longitude: 112.7521,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-workshop-edukids',
    title: 'Jasa Workshop Craft & Edukasi Anak (Offline/Online)',
    description: 'Workshop seru untuk anak usia 4-12 tahun: membuat puzzle, melukis, origami, atau science experiment. Bisa offline di lokasi atau online via Zoom. Min 10 anak.',
    price: 75000, category: 'JASA' as const, stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400&q=80',
    merchantId: 'user-merchant-11', latitude: -7.2575, longitude: 112.7521,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-12 (Glow Local Skincare) ───────────────────────
  {
    id: 'prod-serum-vit-c-lokal',
    title: 'Serum Vitamin C 20% Brightening Local',
    description: 'Serum Vitamin C murni 20% stabilized L-ascorbic acid, diperkaya niacinamide dan hyaluronic acid. BPOM terdaftar, cocok semua jenis kulit. 30ml dengan dropper.',
    price: 125000, category: 'PERAWATAN_KECANTIKAN' as const, stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80',
    merchantId: 'user-merchant-12', latitude: -6.2146, longitude: 106.8451,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-masker-kunyit',
    title: 'Masker Wajah Kunyit & Temulawak Clay Mask',
    description: 'Masker wajah clay berbahan kunyit dan temulawak pilihan, efektif mengecilkan pori dan mencerahkan. Formula 100% natural, tanpa paraben. 60ml jar.',
    price: 65000, category: 'PERAWATAN_KECANTIKAN' as const, stock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=400&q=80',
    merchantId: 'user-merchant-12', latitude: -6.2146, longitude: 106.8451,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-konsultasi-skincare',
    title: 'Konsultasi Skincare Personal Online 1-on-1',
    description: 'Sesi konsultasi 60 menit dengan skincare specialist berpengalaman: analisis jenis kulit, rekomendasi routine, dan solusi masalah kulit spesifik. Via Zoom/WhatsApp.',
    price: 200000, category: 'JASA' as const, stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80',
    merchantId: 'user-merchant-12', latitude: -6.2146, longitude: 106.8451,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-13 (PetCare Indonesia) ──────────────────────────
  {
    id: 'prod-makanan-kucing-premium',
    title: 'Makanan Kucing Grain-Free Premium 1kg',
    description: 'Cat food grain-free dengan protein ayam dan ikan 80%, tanpa jagung/kedelai/gandum. Formula untuk bulu sehat dan pencernaan optimal. Tersedia rasa tuna, salmon, ayam.',
    price: 95000, category: 'TOKO' as const, stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400&q=80',
    merchantId: 'user-merchant-13', latitude: -6.1944, longitude: 106.8229,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-vitamin-anjing',
    title: 'Vitamin & Suplemen Anjing All-in-One 60 Tablet',
    description: 'Suplemen lengkap untuk anjing: multivitamin, omega 3&6, glucosamine, dan probiotik dalam 1 tablet. Untuk sendi, bulu, imunitas, dan pencernaan. Cocok semua ras.',
    price: 125000, category: 'KESEHATAN' as const, stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=80',
    merchantId: 'user-merchant-13', latitude: -6.1944, longitude: 106.8229,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-grooming-pet',
    title: 'Jasa Pet Grooming Home Visit Jakarta',
    description: 'Grooming anjing & kucing ke rumah Anda: mandi, cukur, gunting kuku, bersihkan telinga. Area Jakarta Pusat, Selatan, Timur. Booking min H-1.',
    price: 150000, category: 'JASA' as const, stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80',
    merchantId: 'user-merchant-13', latitude: -6.1944, longitude: 106.8229,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-14 (Kost Premium Menteng) ──────────────────────
  {
    id: 'prod-kost-eksklusif',
    title: 'Sewa Kamar Kost AC WiFi Premium Menteng',
    description: 'Kamar kost mewah di Menteng Jakarta Pusat: AC, WiFi 100Mbps, kamar mandi dalam, dapur bersama, area parkir. Cocok mahasiswa & karyawan. Harga per bulan.',
    price: 3500000, category: 'TOKO' as const, stock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80',
    merchantId: 'user-merchant-14', latitude: -6.1862, longitude: 106.8355,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-cari-kost',
    title: 'Jasa Cari & Survey Kost/Kontrakan Sesuai Budget',
    description: 'Tim kami bantu cari dan survey kost/kontrakan sesuai lokasi, budget, dan kebutuhan Anda. Area Jabodetabek. Gratis jika tidak cocok. Fee sukses Rp 150rb.',
    price: 150000, category: 'JASA' as const, stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=80',
    merchantId: 'user-merchant-14', latitude: -6.1862, longitude: 106.8355,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-interior-kamar',
    title: 'Jasa Dekorasi & Interior Kamar Kost/Apartemen',
    description: 'Transformasi kamar kost atau apartemen Anda menjadi nyaman dan instagramable. Konsultasi desain, pemilihan furnitur, dekorasi, instalasi. Area Jabodetabek.',
    price: 1200000, category: 'JASA' as const, stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80',
    merchantId: 'user-merchant-14', latitude: -6.1862, longitude: 106.8355,
    createdAt: new Date(), updatedAt: new Date(),
  },

  // ─── PRODUK & JASA merchant-15 (Bengkel Pro Autocare) ──────────────────────
  {
    id: 'prod-aksesoris-motor',
    title: 'Paket Aksesoris Motor LED Premium Set',
    description: 'Paket aksesoris motor premium: lampu LED DRL, knalpot racing, handle bar custom, spion oval, footstep racing. Kompatibel Honda, Yamaha, Suzuki. Gratis pasang di bengkel.',
    price: 850000, category: 'OTOMOTIF' as const, stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    merchantId: 'user-merchant-15', latitude: -7.2830, longitude: 112.7372,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-oli-mesin-premium',
    title: 'Oli Mesin Full Synthetic 10W-40 1 Liter',
    description: 'Oli mesin full synthetic kualitas premium, SAE 10W-40, untuk motor 4-tak segala merek. Tahan suhu ekstrem, mengurangi gesekan mesin, umur pakai lebih lama.',
    price: 75000, category: 'OTOMOTIF' as const, stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1635273051427-81d26c65eb97?w=400&q=80',
    merchantId: 'user-merchant-15', latitude: -7.2830, longitude: 112.7372,
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'prod-jasa-servis-motor',
    title: 'Jasa Servis Motor Tune-Up Lengkap + Ganti Oli',
    description: 'Tune-up lengkap motor: bersih karburator/injeksi, stel klep, ganti busi, ganti filter udara, ganti oli mesin + filter. Garansi servis 1 bulan. Antar jemput area Surabaya.',
    price: 185000, category: 'JASA' as const, stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&q=80',
    merchantId: 'user-merchant-15', latitude: -7.2830, longitude: 112.7372,
    createdAt: new Date(), updatedAt: new Date(),
  },
]

export const mockCourses = [
  {
    id: 'course-brand-1',
    title: 'Mastering Digital Branding & Packaging',
    description: 'Panduan lengkap membuat visual identity kelas atas dan kemasan premium yang memikat pelanggan high-end. Dari logo, tipografi, hingga strategi storytelling brand.',
    coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    accessRequired: 'Diamond',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'course-sourdough-1',
    title: 'Artisan Baking & Fermentation Science',
    description: 'Sains di balik ragi alami, teknik folding, pembentukan gluten, dan cara memanggang roti berkualitas gourmet dari dapur skala UMKM.',
    coverImage: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc7b?w=800&q=80',
    accessRequired: 'Platinum',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'course-digital-marketing',
    title: 'Digital Marketing & Social Media Mastery',
    description: 'Strategi pemasaran digital untuk UMKM: Reels, TikTok, Meta Ads, Google SEO, dan copywriting persuasif yang mengkonversi follower menjadi pembeli setia.',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    accessRequired: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'course-kopi-bisnis',
    title: 'Bisnis Kopi: Dari Biji ke Cangkir Profit',
    description: 'Kursus lengkap bisnis kopi UMKM: memilih biji green bean, memahami roasting profile, membuka warung kopi/kedai, dan scaling ke franchise.',
    coverImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80',
    accessRequired: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'course-ecommerce-pro',
    title: 'E-Commerce Pro: Jualan Online Tanpa Modal Besar',
    description: 'Panduan berjualan di marketplace (Tokopedia, Shopee, TikTok Shop) dan membangun toko online sendiri. Termasuk strategi foto produk, pengelolaan stok, dan auto-respond.',
    coverImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    accessRequired: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'course-keuangan-umkm',
    title: 'Keuangan UMKM: Laporan & Cash Flow',
    description: 'Cara mudah mengelola keuangan usaha kecil: membuat laporan laba-rugi sederhana, memahami arus kas, menetapkan harga jual yang benar, dan mengajukan pinjaman UMKM.',
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
    accessRequired: 'Gold',
    createdAt: new Date(), updatedAt: new Date(),
  },
]

export const mockLessons = [
  // course-brand-1
  { id: 'lesson-brand-1', courseId: 'course-brand-1', title: '1. Memahami Audiens Premium & Technical Luxury', content: 'Bagaimana memposisikan brand UMKM Anda agar memiliki daya tarik luxury yang kuat di kalangan menengah ke atas.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 360, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-brand-2', courseId: 'course-brand-1', title: '2. Memilih Palette Warna & Tipografi Sora/Inter', content: 'Mengimplementasikan kombinasi warna gelap/gold dan layout minimalis bergaya Linear pada aset produk digital.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 480, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-brand-3', courseId: 'course-brand-1', title: '3. Desain Logo di Canva & Figma untuk UMKM', content: 'Langkah-langkah membuat logo sederhana namun berdampak tinggi menggunakan Canva Pro atau Figma gratis.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 540, orderIndex: 3, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-brand-4', courseId: 'course-brand-1', title: '4. Desain Kemasan Produk Print-Ready', content: 'Membuat template kemasan produk (label, box, sticker) yang siap cetak dengan dimensi dan bleed yang benar.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 420, orderIndex: 4, createdAt: new Date(), updatedAt: new Date() },
  // course-sourdough-1
  { id: 'lesson-sourdough-1', courseId: 'course-sourdough-1', title: '1. Membuat Starter Ragi Alami (Lievito Madre)', content: 'Panduan hari demi hari memberi makan tepung dan air untuk menangkap ragi liar yang sehat.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 600, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-sourdough-2', courseId: 'course-sourdough-1', title: '2. Teknik Autolyse, Bulk Fermentation & Folding', content: 'Memahami hidrasi adonan, teknik stretch & fold, dan cold retarding agar roti memiliki tekstur pori yang sempurna.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 720, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-sourdough-3', courseId: 'course-sourdough-1', title: '3. Shaping & Scoring Teknik Artisan', content: 'Cara membentuk boule dan batard yang tegang (tight crumb) serta teknik skoring (goresan pisau) yang artistik.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 480, orderIndex: 3, createdAt: new Date(), updatedAt: new Date() },
  // course-digital-marketing
  { id: 'lesson-dm-1', courseId: 'course-digital-marketing', title: '1. Algoritma Instagram & TikTok untuk UMKM', content: 'Memahami cara kerja algoritma dan taktik organik untuk menjangkau ribuan potensi pembeli tanpa biaya ads.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 450, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-dm-2', courseId: 'course-digital-marketing', title: '2. Membuat Konten Reels Viral dengan HP', content: 'Formula konten viral: hook 3 detik, transisi, B-Roll, dan call-to-action yang mendorong share dan purchase.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 390, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-dm-3', courseId: 'course-digital-marketing', title: '3. Meta Ads Tingkat Pemula hingga Lanjutan', content: 'Panduan lengkap Meta Business Suite: targeting audience, budgeting harian, A/B testing creative, dan mengukur ROAS.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 660, orderIndex: 3, createdAt: new Date(), updatedAt: new Date() },
  // course-kopi-bisnis
  { id: 'lesson-kopi-1', courseId: 'course-kopi-bisnis', title: '1. Mengenal Varietas Biji Kopi Nusantara', content: 'Perbedaan antara Arabika, Robusta, dan Liberika dari berbagai daerah: Gayo, Toraja, Flores, Kintamani, Wamena.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 420, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-kopi-2', courseId: 'course-kopi-bisnis', title: '2. Roasting: Light, Medium, Dark & Specialty', content: 'Prinsip dasar roasting, membaca first crack dan second crack, dan cara menentukan profil roast yang sesuai target pasar.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 540, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-kopi-3', courseId: 'course-kopi-bisnis', title: '3. Membuka Kedai Kopi Modal Kecil', content: 'Menghitung modal awal, memilih lokasi strategis, SOP pelayanan, dan strategi retensi pelanggan tetap.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 600, orderIndex: 3, createdAt: new Date(), updatedAt: new Date() },
  // course-ecommerce-pro
  { id: 'lesson-ec-1', courseId: 'course-ecommerce-pro', title: '1. Optimasi Listing Produk Tokopedia & Shopee', content: 'Cara menulis judul produk dengan keyword yang dicari, memilih kategori, dan mengatur harga bersaing secara strategis.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 480, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-ec-2', courseId: 'course-ecommerce-pro', title: '2. Fotografi Produk Profesional dengan HP', content: 'Setup studio mini di rumah dengan budget minim, teknik lighting natural, dan editing foto agar terlihat premium.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 360, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  // course-keuangan-umkm
  { id: 'lesson-keu-1', courseId: 'course-keuangan-umkm', title: '1. Memisahkan Keuangan Usaha dan Pribadi', content: 'Mengapa rekening terpisah penting, cara membuka rekening bisnis, dan menetapkan gaji untuk diri sendiri sebagai pemilik.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 300, orderIndex: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-keu-2', courseId: 'course-keuangan-umkm', title: '2. Membuat Laporan Laba-Rugi Sederhana', content: 'Template Google Sheets gratis untuk mencatat pemasukan, pengeluaran, HPP, dan laba bersih mingguan/bulanan.', videoUrl: 'https://www.w3schools.com/html/movie.mp4', duration: 420, orderIndex: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'lesson-keu-3', courseId: 'course-keuangan-umkm', title: '3. Cara Menghitung Harga Jual yang Tepat', content: 'Formula HPP + biaya overhead + profit margin yang sehat. Bagaimana menyesuaikan harga tanpa takut kehilangan pelanggan.', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', duration: 360, orderIndex: 3, createdAt: new Date(), updatedAt: new Date() },
]

export const mockProgress: Array<{ userId: string; lessonId: string; completed: boolean }> = [
  { userId: 'user-customer-1', lessonId: 'lesson-brand-1', completed: true },
  { userId: 'user-customer-1', lessonId: 'lesson-dm-1', completed: true },
  { userId: 'user-customer-1', lessonId: 'lesson-dm-2', completed: true },
  { userId: 'user-merchant-1', lessonId: 'lesson-sourdough-1', completed: true },
  { userId: 'user-merchant-1', lessonId: 'lesson-sourdough-2', completed: true },
  { userId: 'user-merchant-1', lessonId: 'lesson-kopi-1', completed: true },
  { userId: 'user-merchant-1', lessonId: 'lesson-kopi-2', completed: true },
]
export const mockGroups = [
  {
    id: 'group-umum',
    name: 'Forum Umum Saloka.id',
    description: 'Grup diskusi utama pelaku usaha Saloka.id. Bagikan pengalaman, tips bisnis, tanya jawab seputar perpajakan, hukum, logistik, dan pengembangan startup Anda.',
    coverUrl: null,
    avatarUrl: null,
    isSuspended: false,
    adminId: 'user-admin-1', // Super Admin
    createdAt: new Date(Date.now() - 3600000 * 240),
    updatedAt: new Date(Date.now() - 3600000 * 240),
  },
  {
    id: 'group-kopi',
    name: 'Pedagang Kopi & Roastery Indonesia',
    description: 'Tempat bertemunya petani kopi, pemilik warung kopi, roastery artisan, dan pecinta kopi se-Indonesia. Diskusikan harga biji kopi, teknik roasting, dan review alat kopi.',
    coverUrl: null,
    avatarUrl: null,
    isSuspended: false,
    adminId: 'user-merchant-1', // Kala Sourdough
    createdAt: new Date(Date.now() - 3600000 * 120),
    updatedAt: new Date(Date.now() - 3600000 * 120),
  },
  {
    id: 'group-fashion',
    name: 'Komunitas Industri Fashion & Tekstil',
    description: 'Diskusikan supplier kain murah Bandung, pola jahitan premium, trend warna, konveksi seragam, sablon digital, dan ekspor produk garment lokal.',
    coverUrl: null,
    avatarUrl: null,
    isSuspended: false,
    adminId: 'user-merchant-2', // Nusantara Fashion
    createdAt: new Date(Date.now() - 3600000 * 80),
    updatedAt: new Date(Date.now() - 3600000 * 80),
  }
]

export const mockGroupMembers = [
  // Seed all mock users to group-umum
  ...mockUsers.map((u, i) => ({
    id: `gm-seed-${i}`,
    groupId: 'group-umum',
    userId: u.id,
    createdAt: new Date()
  })),
  // Seed some users to group-kopi
  { id: 'gm-k1', groupId: 'group-kopi', userId: 'user-merchant-1', createdAt: new Date() },
  { id: 'gm-k2', groupId: 'group-kopi', userId: 'user-customer-1', createdAt: new Date() },
  { id: 'gm-k3', groupId: 'group-kopi', userId: 'user-merchant-3', createdAt: new Date() },
  // Seed some to group-fashion
  { id: 'gm-f1', groupId: 'group-fashion', userId: 'user-merchant-2', createdAt: new Date() },
  { id: 'gm-f2', groupId: 'group-fashion', userId: 'user-customer-1', createdAt: new Date() },
]

export const mockPosts = [
  {
    id: 'post-komunitas-tukang-1',
    title: '[Komunitas Tukang] Tips negosiasi harga material bangunan 2026',
    content: 'Halo teman-teman tukang dan kontraktor! Saya mau berbagi tips: coba bandingkan harga di 3 toko bangunan sebelum beli. Biasanya ada selisih 15-20% untuk pasir, batu, dan besi. Siapa punya pengalaman beli grosir langsung ke pabrik?',
    authorId: 'user-merchant-1',
    createdAt: new Date(Date.now() - 3600000 * 1),
    updatedAt: new Date(Date.now() - 3600000 * 1),
  },
  {
    id: 'post-komunitas-kopi-1',
    title: '[Komunitas Pedagang Kopi] Roaster lokal vs import — mana lebih untung?',
    content: 'Setelah 2 tahun jualan kopi, saya akhirnya memilih roaster lokal Gayo. Margin lebih besar, pengiriman lebih cepat, dan bisa custom roast level sesuai pesanan. Teman-teman yang jual kopi, gimana pengalaman kalian?',
    authorId: 'user-affiliate-1',
    createdAt: new Date(Date.now() - 3600000 * 3),
    updatedAt: new Date(Date.now() - 3600000 * 3),
  },
  {
    id: 'post-komunitas-kuliner-1',
    title: '[Komunitas Kuliner] Cara dapetin sertifikat PIRT untuk produk rumahan',
    content: 'Proses sertifikasi PIRT (Pangan Industri Rumah Tangga) di dinas setempat ternyata tidak sesulit yang dibayangkan. Butuh sekitar 2 minggu dan biaya sekitar Rp 300rb. Saya bagikan langkah-langkah detailnya di sini.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 6),
    updatedAt: new Date(Date.now() - 3600000 * 6),
  },
  {
    id: 'post-komunitas-fashion-1',
    title: '[Komunitas Fashion Lokal] Supplier bahan kain murah berkualitas Bandung',
    content: 'Mau share info supplier kain katun premium di Pasar Baru Bandung. Minimum order 5 meter, harga mulai Rp 18.000/meter untuk katun TC 133x72. Cocok banget untuk yang baru mulai usaha baju. DM kalau butuh kontaknya!',
    authorId: 'user-merchant-1',
    createdAt: new Date(Date.now() - 3600000 * 10),
    updatedAt: new Date(Date.now() - 3600000 * 10),
  },
  {
    id: 'post-1',
    title: 'Bagaimana cara menaikkan harga produk UMKM tanpa kehilangan pelanggan?',
    content: 'Saya memiliki usaha bakery skala rumahan, ingin mengubah kemasan menjadi premium/luxury dan menaikkan harga jual 50%. Ada saran untuk brandingnya? Sudah coba beberapa kali tapi selalu ada pelanggan yang komplain harga naik.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 2),
    updatedAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: 'post-2',
    title: 'Panduan lengkap mendaftarkan sertifikasi Halal dan BPOM 2026',
    content: 'Halo kawan-kawan, berikut adalah langkah demi langkah gratis bagi pelaku UMKM di Saloka untuk mendaftarkan merek produk makanan di sistem dinas. Proses online bisa melalui website BPOM dan Halal.go.id. Anggaran siapkan sekitar Rp 500rb-2jt tergantung jenis produk.',
    authorId: 'user-merchant-1',
    createdAt: new Date(Date.now() - 3600000 * 12),
    updatedAt: new Date(Date.now() - 3600000 * 12),
  },
  {
    id: 'post-komunitas-tukang-2',
    title: '[Komunitas Tukang] Harga borongan cat rumah per meter persegi 2026',
    content: 'Update harga borongan cat per Juni 2026: cat dinding dalam Rp 35-45rb/m², luar Rp 50-65rb/m² sudah termasuk cat 2 lapis. Cat kayu Rp 40-55rb/m². Harga sudah naik ~10% dari tahun lalu karena biaya tukang naik.',
    authorId: 'user-affiliate-1',
    createdAt: new Date(Date.now() - 3600000 * 20),
    updatedAt: new Date(Date.now() - 3600000 * 20),
  },
  {
    id: 'post-komunitas-digital-1',
    title: '[Komunitas Digital] Tips jualan di TikTok Shop tanpa stok barang (dropship)',
    content: 'Sudah 3 bulan jualan di TikTok Shop dengan sistem dropship dari supplier Cina dan lokal. Omzet bulan ini Rp 8 juta, profit bersih sekitar 25%. Kuncinya: pilih produk trending, buat konten review jujur, dan respon komentar cepat.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 28),
    updatedAt: new Date(Date.now() - 3600000 * 28),
  },
  // ─── Posts dari 10 merchant baru ────────────────────────────────────────────
  {
    id: 'post-herbal-tips',
    title: '🌿 Herbal Nusantara: 5 Tanaman Obat yang Wajib Ada di Rumah UMKM Kuliner',
    content: 'Sebagai pengusaha herbal dari Bandung, saya mau share 5 tanaman obat yang selalu saya rekomendasikan: 1) Jahe merah — anti-inflamasi dan imunitas, 2) Temulawak — kesehatan hati, 3) Kunyit — antioksidan alami, 4) Sambiloto — diabetes dan kolesterol, 5) Kayu manis — gula darah stabil. Semua bisa jadi produk UMKM yang laku! Siapa yang sudah coba produksi sendiri?',
    authorId: 'user-merchant-6',
    createdAt: new Date(Date.now() - 3600000 * 5),
    updatedAt: new Date(Date.now() - 3600000 * 5),
  },
  {
    id: 'post-furni-branding',
    title: '🪑 Furnicraft Jepara: Cara kami jual kursi Rp 8 juta dan tetap laris di marketplace',
    content: 'Banyak yang tanya, gimana bisa jual produk mahal di marketplace yang penuh perang harga? Jawaban kami: storytelling + foto profesional + video proses pembuatan. Kami rekam pengrajin ukir kami yang sudah 30 tahun berkarya, lalu upload ke TikTok dan Instagram. Hasilnya? Inquiry dari Singapura dan Malaysia juga masuk! Kunci: jual keunikan dan proses, bukan hanya produk.',
    authorId: 'user-merchant-7',
    createdAt: new Date(Date.now() - 3600000 * 8),
    updatedAt: new Date(Date.now() - 3600000 * 8),
  },
  {
    id: 'post-agro-urban',
    title: '🥦 AgroSegar: Urban farming bisa dimulai dengan lahan 2x2 meter!',
    content: 'Banyak yang mikir urban farming butuh lahan luas. Padahal dengan sistem vertikal di balkon atau rooftop 2x2 meter, bisa panen 5-8 kg sayur per minggu! Saya mulai dari pot bekas dan paralon PVC, sekarang sudah supply 20+ keluarga langganan di Bogor. Yang mau belajar, saya buka workshop online setiap Sabtu. Gratis untuk member Saloka.id!',
    authorId: 'user-merchant-8',
    createdAt: new Date(Date.now() - 3600000 * 14),
    updatedAt: new Date(Date.now() - 3600000 * 14),
  },
  {
    id: 'post-silver-ekspor',
    title: '💍 Silver Artisan Celuk: Pengalaman ekspor perhiasan perak ke Eropa pertama kali',
    content: 'Tahun lalu kami berhasil ekspor pertama ke buyer dari Belanda — 200 pcs cincin dan gelang perak. Prosesnya tidak mudah: perlu sertifikat uji kandungan logam, phytosanitary, dan invoice khusus. Tapi hasilnya worth it! Margin ekspor 3x lipat dari penjualan lokal. Siapa yang tertarik diskusi soal proses ekspor kerajinan? Saya siap share pengalaman!',
    authorId: 'user-merchant-9',
    createdAt: new Date(Date.now() - 3600000 * 22),
    updatedAt: new Date(Date.now() - 3600000 * 22),
  },
  {
    id: 'post-konveksi-tips',
    title: '👕 Konveksi Solo: Cara hitung harga jual konveksi agar tidak rugi',
    content: 'Banyak pemula konveksi yang rugi karena salah hitung HPP. Formula sederhana: HPP = (Biaya Bahan + Upah Jahit + Overhead + Sablon/Bordir) ÷ Jumlah Pcs. Jangan lupa tambah margin 30-40% untuk profit. Contoh: kaos polos bahan Rp 15rb, jahit Rp 8rb, overhead Rp 3rb, sablon Rp 12rb = HPP Rp 38rb. Jual minimal Rp 55rb untuk margin sehat. Semoga membantu!',
    authorId: 'user-merchant-10',
    createdAt: new Date(Date.now() - 3600000 * 30),
    updatedAt: new Date(Date.now() - 3600000 * 30),
  },
  {
    id: 'post-edukids-bisnis',
    title: '🧩 EduKids: Bisnis mainan edukasi — pasar yang masih sangat terbuka lebar!',
    content: 'Riset kami menunjukkan pasar mainan edukasi anak Indonesia tumbuh 18% per tahun. Sayangnya 80% masih diisi produk impor. Ini peluang besar untuk UMKM lokal! Kunci sukses kami: 1) Bahan ramah lingkungan (kayu mahoni lokal), 2) Desain bermuatan budaya Indonesia, 3) Kemasan premium dengan panduan bermain. Produk pertama kami puzzle peta Indonesia langsung sold out di minggu pertama!',
    authorId: 'user-merchant-11',
    createdAt: new Date(Date.now() - 3600000 * 36),
    updatedAt: new Date(Date.now() - 3600000 * 36),
  },
  {
    id: 'post-skincare-bpom',
    title: '✨ Glow Local: Cara daftar BPOM produk skincare UMKM — panduan lengkap 2026',
    content: 'Setelah 8 bulan perjuangan, serum vitamin C kami akhirnya dapat nomor BPOM! Ini yang perlu disiapkan: 1) Sertifikat CPKB (Cara Produksi Kosmetik yang Baik), 2) Uji stabilitas produk di lab terakreditasi (±Rp 3-5 juta), 3) Uji keamanan (patch test), 4) Notifikasi online di e-bpom.pom.go.id (Rp 100rb/produk). Total biaya sekitar Rp 8-15 juta tapi SANGAT worth it untuk kepercayaan konsumen!',
    authorId: 'user-merchant-12',
    createdAt: new Date(Date.now() - 3600000 * 48),
    updatedAt: new Date(Date.now() - 3600000 * 48),
  },
  {
    id: 'post-petcare-tips',
    title: '🐾 PetCare: 5 tanda kucing/anjing Anda butuh grooming segera',
    content: 'Sebagai pet groomer profesional, ini tanda hewan peliharaan Anda butuh grooming: 1) Bulu kusut dan berbau, 2) Kuku panjang sampai melengkung, 3) Telinga berbau atau kotor, 4) Kulit gatal-gatal dan berketombe, 5) Mata berair terus-menerus. Grooming rutin bukan cuma soal penampilan, tapi kesehatan! Anjing idealnya grooming setiap 4-6 minggu, kucing setiap 6-8 minggu.',
    authorId: 'user-merchant-13',
    createdAt: new Date(Date.now() - 3600000 * 55),
    updatedAt: new Date(Date.now() - 3600000 * 55),
  },
  {
    id: 'post-properti-kost',
    title: '🏠 Tips investasi kost-kostan untuk pemula UMKM properti',
    content: 'Kost-kostan adalah passive income terbaik untuk UMKM properti. Tips dari pengalaman 5 tahun: 1) Pilih lokasi dekat kampus/perkantoran, 2) Minimal 10 kamar untuk break-even yang baik, 3) Fasilitaskan AC + WiFi = bisa pasang harga premium, 4) Manajemen via aplikasi (ada banyak yang gratis), 5) ROI rata-rata 8-12% per tahun. Siapa yang tertarik mulai bisnis properti skala kecil?',
    authorId: 'user-merchant-14',
    createdAt: new Date(Date.now() - 3600000 * 62),
    updatedAt: new Date(Date.now() - 3600000 * 62),
  },
  {
    id: 'post-bengkel-otomotif',
    title: '🔧 Bengkel Pro: Tips rawat motor agar awet 10 tahun+ — dari mekanik berpengalaman',
    content: 'Sebagai bengkel dengan 15 tahun pengalaman, ini rahasia motor awet: 1) Ganti oli setiap 2.000km atau 2 bulan (jangan nunggu hitam!), 2) Cek tekanan ban setiap 2 minggu, 3) Servis rutin setiap 6.000km, 4) Jangan abaikan bunyi aneh — lebih murah servis awal daripada rusak parah, 5) Pakai spare part ori/KW1, jangan KW3. Motor dengan perawatan baik bisa bertahan 15-20 tahun!',
    authorId: 'user-merchant-15',
    createdAt: new Date(Date.now() - 3600000 * 70),
    updatedAt: new Date(Date.now() - 3600000 * 70),
  },
]

export const mockComments = [
  {
    id: 'comment-1',
    postId: 'post-1',
    content: 'Coba gunakan box tebal berserat hitam matte, lalu gunakan tinta foil emas (gold hotprint) untuk logo. Sentuhan visual ini instan membuat produk terasa 5x lebih berharga.',
    authorId: 'user-merchant-1',
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'comment-2',
    postId: 'post-1',
    content: 'Tambahkan cerita (storytelling) di label kemasan: asal bahan baku, tanggal produksi, dan dedikasi tangan-tangan artisan. Pelanggan premium membeli VALUE, bukan sekadar produk.',
    authorId: 'user-affiliate-1',
    createdAt: new Date(Date.now() - 3600000 * 0.5),
    updatedAt: new Date(Date.now() - 3600000 * 0.5),
  },
  {
    id: 'comment-3',
    postId: 'post-komunitas-tukang-1',
    content: 'Saya biasanya langsung ke distributor di kawasan industri. Hemat 20-30% dibanding toko bangunan eceran. Butuh mobil pick-up tapi worth it kalau pesan banyak.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 0.75),
    updatedAt: new Date(Date.now() - 3600000 * 0.75),
  },
  {
    id: 'comment-4',
    postId: 'post-komunitas-kopi-1',
    content: 'Setuju banget! Roaster lokal juga lebih mudah dikomunikasikan soal SCA score dan flavor notes. Saya pakai roaster dari Toraja, bisa order mulai 2kg. Quality control jauh lebih ketat dari import.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 2.5),
    updatedAt: new Date(Date.now() - 3600000 * 2.5),
  },
  {
    id: 'comment-5',
    postId: 'post-2',
    content: 'Saya sudah coba daftar PIRT bulan lalu. Prosesnya ada pelatihan keamanan pangan dulu (1 hari), lalu inspeksi dapur, baru sertifikat keluar sekitar 10 hari kerja. Gratis atau biaya sangat murah di beberapa daerah!',
    authorId: 'user-affiliate-1',
    createdAt: new Date(Date.now() - 3600000 * 11),
    updatedAt: new Date(Date.now() - 3600000 * 11),
  },
  {
    id: 'comment-6',
    postId: 'post-herbal-tips',
    content: 'Wah, saya ada tanaman jahe merah di belakang rumah dan belum dimanfaatkan optimal. Bisa bantu info cara bikin produk jahe merah siap jual yang awet tanpa pengawet kimia?',
    authorId: 'user-merchant-8',
    createdAt: new Date(Date.now() - 3600000 * 4),
    updatedAt: new Date(Date.now() - 3600000 * 4),
  },
  {
    id: 'comment-7',
    postId: 'post-herbal-tips',
    content: 'Kunyit juga bisa dijadikan sabun dan masker loh! Margin produk turunan herbal jauh lebih tinggi dari jual bahan mentah. Saya jual masker kunyit dan hasilnya 5x lebih untung.',
    authorId: 'user-merchant-12',
    createdAt: new Date(Date.now() - 3600000 * 3),
    updatedAt: new Date(Date.now() - 3600000 * 3),
  },
  {
    id: 'comment-8',
    postId: 'post-furni-branding',
    content: 'Betul sekali! Kami jual kerajinan perak dan strategi yang sama kami terapkan. Video pengrajin tua kami yang sudah 40 tahun bikin perhiasan bisa jutaan views di Reels. Authentic content memang tak ternilai.',
    authorId: 'user-merchant-9',
    createdAt: new Date(Date.now() - 3600000 * 7),
    updatedAt: new Date(Date.now() - 3600000 * 7),
  },
  {
    id: 'comment-9',
    postId: 'post-agro-urban',
    content: 'Urban farming memang seru! Saya sudah 1 tahun tanam sayur di atap rumah kontrakan. Tips tambahan: pakai media sekam bakar + cocopeat untuk hasil maksimal dan drainase bagus.',
    authorId: 'user-customer-1',
    createdAt: new Date(Date.now() - 3600000 * 12),
    updatedAt: new Date(Date.now() - 3600000 * 12),
  },
  {
    id: 'comment-10',
    postId: 'post-skincare-bpom',
    content: 'Makasih infonya sangat detail! Satu pertanyaan: apakah produk yang sudah ada PIRT bisa langsung upgrade ke BPOM atau harus mulai dari nol? Produk saya lotion herbal.',
    authorId: 'user-merchant-6',
    createdAt: new Date(Date.now() - 3600000 * 45),
    updatedAt: new Date(Date.now() - 3600000 * 45),
  },
  {
    id: 'comment-11',
    postId: 'post-skincare-bpom',
    content: 'PIRT dan BPOM itu jalurnya berbeda. PIRT untuk makanan/minuman, BPOM Notifikasi untuk kosmetik. Jadi lotion herbal langsung ke BPOM Notifikasi, tidak perlu PIRT dulu. Semangat!',
    authorId: 'user-merchant-12',
    createdAt: new Date(Date.now() - 3600000 * 44),
    updatedAt: new Date(Date.now() - 3600000 * 44),
  },
  {
    id: 'comment-12',
    postId: 'post-konveksi-tips',
    content: 'Formula HPP-nya sangat membantu! Selama ini saya hitung kasar-kasaran saja dan sering merasa tidak untung padahal orderan banyak. Ternyata biaya overhead yang sering dilupakan.',
    authorId: 'user-merchant-10',
    createdAt: new Date(Date.now() - 3600000 * 28),
    updatedAt: new Date(Date.now() - 3600000 * 28),
  },
  {
    id: 'comment-13',
    postId: 'post-bengkel-otomotif',
    content: 'Setuju soal ganti oli rutin! Pelanggan saya yang rajin ganti oli setiap 2000km motornya masih prima di 150.000km. Yang jarang ganti, di 80.000km sudah butuh overhaul mesin.',
    authorId: 'user-merchant-15',
    createdAt: new Date(Date.now() - 3600000 * 68),
    updatedAt: new Date(Date.now() - 3600000 * 68),
  },
]

export const mockWallets = [
  {
    id: 'wallet-merchant',
    userId: 'user-merchant-1',
    balance: 4850000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'wallet-affiliate',
    userId: 'user-affiliate-1',
    balance: 850000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'wallet-customer',
    userId: 'user-customer-1',
    balance: 200000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 'wallet-m2', userId: 'user-merchant-2', balance: 2100000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m3', userId: 'user-merchant-3', balance: 3750000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m4', userId: 'user-merchant-4', balance: 1820000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m5', userId: 'user-merchant-5', balance: 5200000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m6', userId: 'user-merchant-6', balance: 980000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m7', userId: 'user-merchant-7', balance: 12500000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m8', userId: 'user-merchant-8', balance: 650000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m9', userId: 'user-merchant-9', balance: 4300000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m10', userId: 'user-merchant-10', balance: 2850000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m11', userId: 'user-merchant-11', balance: 740000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m12', userId: 'user-merchant-12', balance: 3100000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m13', userId: 'user-merchant-13', balance: 1250000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m14', userId: 'user-merchant-14', balance: 8900000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-m15', userId: 'user-merchant-15', balance: 2200000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-affiliate-2', userId: 'user-affiliate-2', balance: 350000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-affiliate-3', userId: 'user-affiliate-3', balance: 150000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-customer-2', userId: 'user-customer-2', balance: 50000, createdAt: new Date(), updatedAt: new Date() },
  { id: 'wallet-customer-3', userId: 'user-customer-3', balance: 25000, createdAt: new Date(), updatedAt: new Date() },
]

export const mockWalletTransactions = [
  {
    id: 'tx-1',
    walletId: 'wallet-merchant',
    amount: 150000,
    type: 'SALE' as const,
    description: 'Penjualan Kopi Gayo Organik Premium',
    createdAt: new Date(Date.now() - 3600000 * 3),
  },
  {
    id: 'tx-2',
    walletId: 'wallet-affiliate',
    amount: 75000,
    type: 'COMMISSION' as const,
    description: 'Komisi Referal Penjualan Kopi Gayo',
    createdAt: new Date(Date.now() - 3600000 * 3),
  },
  {
    id: 'tx-3',
    walletId: 'wallet-affiliate',
    amount: 15000,
    type: 'COMMISSION' as const,
    description: 'Komisi Affiliate Tier 2 dari penjualan Jasa Konsultasi',
    createdAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: 'tx-4',
    walletId: 'wallet-affiliate-2',
    amount: 50000,
    type: 'COMMISSION' as const,
    description: 'Komisi Affiliate Tier 1 dari penjualan Jasa Konsultasi',
    createdAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: 'tx-5',
    walletId: 'wallet-affiliate-2',
    amount: 10000,
    type: 'COMMISSION' as const,
    description: 'Komisi Affiliate Tier 2 dari penjualan Kemeja Batik',
    createdAt: new Date(Date.now() - 3600000 * 1),
  },
  {
    id: 'tx-6',
    walletId: 'wallet-affiliate-3',
    amount: 35000,
    type: 'COMMISSION' as const,
    description: 'Komisi Affiliate Tier 1 dari penjualan Kemeja Batik',
    createdAt: new Date(Date.now() - 3600000 * 1),
  }
]

export const mockReferrals = [
  {
    id: 'ref-1',
    affiliateId: 'user-affiliate-1',
    buyerId: 'user-customer-1',
    amount: 75000,
    status: 'PAID' as const,
    createdAt: new Date(Date.now() - 3600000 * 3),
    updatedAt: new Date(Date.now() - 3600000 * 3),
  },
  {
    id: 'ref-2',
    affiliateId: 'user-affiliate-2',
    buyerId: 'user-customer-2',
    amount: 50000,
    status: 'PAID' as const,
    createdAt: new Date(Date.now() - 3600000 * 2),
    updatedAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: 'ref-3',
    affiliateId: 'user-affiliate-1',
    buyerId: 'user-customer-2',
    amount: 15000,
    status: 'PAID' as const,
    createdAt: new Date(Date.now() - 3600000 * 2),
    updatedAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: 'ref-4',
    affiliateId: 'user-affiliate-3',
    buyerId: 'user-customer-3',
    amount: 35000,
    status: 'PAID' as const,
    createdAt: new Date(Date.now() - 3600000 * 1),
    updatedAt: new Date(Date.now() - 3600000 * 1),
  },
  {
    id: 'ref-5',
    affiliateId: 'user-affiliate-2',
    buyerId: 'user-customer-3',
    amount: 10000,
    status: 'PAID' as const,
    createdAt: new Date(Date.now() - 3600000 * 1),
    updatedAt: new Date(Date.now() - 3600000 * 1),
  }
]
